# -*- coding: utf-8 -*-
"""Proyecto 2 - PA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_B4jzoZxHFYpgVpsyV6kHxN0tTkxkk9M

##PROYECTO 2
###PARTE 1

###EJERCICIO 1
####Escribir una función que reciba como parámetros dos strings, uno contendrá la ruta para acceder a una imagen (Drive o URL), y el otro una palabra clave, que podrá ser “Youtube, Instagram, Twitter o Facebook”. La función debe leer/abrir la foto y redimensionar la imagen al tamaño adecuado especificado como parámetro para cada una de las palabras clave (busque las dimensiones recomendadas de cada aplicación).
Nota: Tenga en cuenta la escala, no queremos que la foto se distorsione.
"""



from PIL import Image # Importamos el modulo Image de Pillow para poder trabajar



ruta_imagen = "./imagenes/"

def redimensionar_imagen(ruta, keyword):
  """
    Redimensiona una imagen según la keyword
    pasada como parámetro
  """

  img = Image.open(ruta)


  # Definimos el dict con los valores de cada kw
  # (Valores estimados según Google)
  kw_dict = {
      "youtube": (1280, 720),
      "instagram": (1080,1350),
      "twitter": (1600,900),
      "facebook": (1200,630)
  }

  # Verificamos si la keyword es válida
  if keyword.lower() in kw_dict.keys():
    # Si existe, obtenemos el ancho y alto correspondiente
    ancho, alto = kw_dict[keyword.lower()]

  else:
    # Si no, devolvemos valores Default
    ancho, alto = (1280,1280)

  # Desempaquetamos ancho y alto originales de la imagen
  ancho_orig, alto_orig = img.size

  # Calculamos cuanto hay que agrandar la imagen sin deformarla
  ratio = max(ancho / ancho_orig, alto / alto_orig)

  # Definimos los nuevos valores
  nuevo_ancho = int(ancho_orig * ratio)
  nuevo_alto = int(alto_orig * ratio)

  img_resized = img.resize((nuevo_ancho, nuevo_alto), Image.Resampling.LANCZOS)


  img_resized.save(ruta_imagen + "imagen_redimensionada.jpg")

"""###EJERCICIO 2
####Crear una función que ajuste el contraste de la foto utilizando su histograma. Probarla con una foto oscura y con otra con exceso de luz. Mostrar la foto original y la ecualizada en una misma figura y guardarla en ambos casos (Adjuntar las figuras a la solución del proyecto).
"""

import matplotlib.pyplot as plt
import numpy as np

def ajustar_contraste(ruta):
  """
    Ajusta el contraste de una foto
    mediante su histograma
  """
  try:
    img_original = Image.open(ruta)

    # Convertimos a escala de grises
    img = img_original.convert("L")

    # Convertimos a un array numpy
    pix = np.array(img)


    # Calculamos el histograma
    hist, bins = np.histogram(pix.flatten(), bins=256, range=[0,256]) # type: ignore

    # Calculamos la distribucion acumulada
    distribucion_acumulada = hist.cumsum()

    # Normalizamos la distribucion acumulada
    distribucion_acum_normalizada = 255 * distribucion_acumulada / distribucion_acumulada[-1]

    # Ajustamos el contraste
    img_ecualizada = distribucion_acum_normalizada[pix]

    # Creamos la figura para mostrar el resultado
    fig, ax = plt.subplots(1, 2, figsize=(12,5))
    ax[0].imshow(img_original)
    ax[0].axis(False)
    ax[0].set_title("Original")
    ax[1].imshow(img_ecualizada)
    ax[1].axis(False)
    ax[1].set_title("Ajustada")

    plt.tight_layout()

    fig.savefig(ruta_imagen + "imagen_ajustada.jpg")
    #plt.show()
    plt.close(fig)
    return img_ecualizada




  except Exception as e:
    print(f"Error al ajustar el contraste: {e}")
    return

"""###EJERCICIO 3
####Programar una función que aplique los 9 filtros de Pillow de la siguiente tabla. La función debe incluir en sus parámetros el nombre del filtro que el usuario quiere usar. Mostrar y guardar la foto resultante. Además, mostrar la foto original y las 9 resultantes si se aplicaran todos los filtros en una misma figura y guardarla en ambos casos.
Filtros: ORIGINAL, BLUR, CONTOUR, DETAIL, EDGE_ENHANCE, EDGE_ENHANCE_MORE, EMBOSS, FIND_EDGES, SHARPEN, SMOOTH
Nota: Ponerle como título a cada foto el nombre del filtro, e indicar al usuario cuál fue el filtro que eligió (por ejemplo con el color del título diferente).
"""

from PIL import Image, ImageFilter
import matplotlib.pyplot as plt

def aplicar_filtros(ruta, filtro_elegido='ORIGINAL'):
    """
    Aplica filtros de Pillow a una imagen.
    Parámetros:
    - ruta: ruta de la imagen a procesar
    - filtro_elegido: nombre del filtro a aplicar (por defecto 'ORIGINAL')
    """
    # Diccionario de filtros disponibles
    filtros = {
        'ORIGINAL': None,
        'BLUR': ImageFilter.BLUR,
        'CONTOUR': ImageFilter.CONTOUR,
        'DETAIL': ImageFilter.DETAIL,
        'EDGE_ENHANCE': ImageFilter.EDGE_ENHANCE,
        'EDGE_ENHANCE_MORE': ImageFilter.EDGE_ENHANCE_MORE,
        'EMBOSS': ImageFilter.EMBOSS,
        'FIND_EDGES': ImageFilter.FIND_EDGES,
        'SHARPEN': ImageFilter.SHARPEN,
        'SMOOTH': ImageFilter.SMOOTH
    }

    # Validar que el filtro existe
    filtro_elegido = filtro_elegido.upper()
    if filtro_elegido not in filtros:
        print(f"Filtro '{filtro_elegido}' no valido. Filtros disponibles: {list(filtros.keys())}")
        return
    
    # Cargar imagen original
    img_original = Image.open(ruta)
    # Aplicar el filtro elegido
    if filtros[filtro_elegido] is None:
        img_filtrada = img_original
    else:
        img_filtrada = img_original.filter(filtros[filtro_elegido])

    # Mostrar y guardar la imagen con el filtro elegido
    plt.figure(figsize=(8, 6))
    plt.imshow(img_filtrada)
    plt.title(f'Filtro: {filtro_elegido}', fontsize=16, color='red', fontweight='bold')
    plt.axis('off')
    plt.tight_layout()
    plt.savefig(ruta_imagen + f"imagen_{filtro_elegido.lower()}.jpg", dpi=150, bbox_inches='tight')
    plt.show()

    # Crear figura con todos los filtros
    fig, axes = plt.subplots(2, 5, figsize=(20, 8))
    fig.suptitle('\nComparación de todos los filtros', fontsize=18, fontweight='bold')
    axes = axes.flatten()

    for idx, (nombre_filtro, filtro) in enumerate(filtros.items()):
        # Aplicar filtro
        if filtro is None:
            img_temp = img_original
        else:
            img_temp = img_original.filter(filtro)
        # Mostrar en subplot
        axes[idx].imshow(img_temp)
        # Color del título: rojo si es el filtro elegido, negro si no
        color_titulo = 'red' if nombre_filtro == filtro_elegido else 'black'
        peso_titulo = 'bold' if nombre_filtro == filtro_elegido else 'normal'
        axes[idx].set_title(nombre_filtro, fontsize=12, color=color_titulo, fontweight=peso_titulo)
        axes[idx].axis('off')
    plt.tight_layout()
    plt.savefig(ruta_imagen + 'todos_filtros.jpg', dpi=150, bbox_inches='tight')
    plt.show()


"""###EJERCICIO 4
####Caso hipotético: Se llevó a cabo un análisis de usuarios que demostró que el 35% de los posibles futuros usuarios son pintores que compartirían fotos de sus trabajos allí, por lo cual les pedimos que diseñen una funcionalidad en Python para asistirlos.
El objetivo es que cuando el algoritmo identifica con IA que la foto leída es de una persona (suponga que hay otra función que ya ha hecho este paso previo con una variable persona=True), ayude a los usuarios a dibujar el boceto de la persona de la foto. Prueben su función con una foto de un personaje de su elección.
"""

from PIL import ImageFilter, ImageOps, ImageEnhance

def boceto_persona(ruta, persona=True, invertir=True):
    if not persona:
        print("No se detectó una persona, no se aplican filtros.")
        return Image.open(ruta)


    # Abrimos imagen y convertimos a escala de grises
    img = Image.open(ruta)

    gris = img.convert("L")

    # Aplicamos desenfoque
    blur = gris.filter(ImageFilter.GaussianBlur(radius=2))

    # Detección bordes
    edges = blur.filter(ImageFilter.FIND_EDGES)

    # Inversión para tener líneas blancas
    if invertir:
        edges = ImageOps.invert(edges)

    # Aumento de contraste
    enhancer = ImageEnhance.Contrast(edges)
    boceto = enhancer.enhance(2.5)


    # Creacion de figuras para mostrar los resultados
    plt.figure(figsize=(10,5))
    plt.subplot(1,2,1)
    plt.title("Original")
    plt.imshow(img)
    plt.axis("off")

    plt.subplot(1,2,2)
    plt.title("Boceto generado")
    plt.imshow(boceto, cmap="gray")
    plt.axis("off")
    plt.savefig(ruta_imagen + "boceto.jpg", dpi=150, bbox_inches='tight')
    #plt.show()
    plt.close()
    return

"""###EJERCICIO 5
####Crear un menú de opciones que le permita al usuario hacer todas las operaciones, tener en cuenta que para todas las opciones es necesario pasar primero por la función 1, por lo cual, asistan al usuario para que no se salte la lectura de las imágenes y usen excepciones en sus funciones para validarlo.
"""

# Carga de imagen de una carpeta de colab
import os

ruta_imagen_cargada = None

def cargar_imagen():
    """
    Carga una imagen desde una carpeta de colab.
    """
    
    global ruta_imagen_cargada
    nombre = input("Ingrese el nombre del archivo (por ejemplo, foto.jpg): ").strip()

    ruta_completa = os.path.join(ruta_imagen, nombre)

    if not nombre:
        print("No se subió ningún archivo.")
        return None

    try:
        Image.open(ruta_completa)
        print("Imagen cargada correctamente:", nombre)
        ruta_imagen_cargada = ruta_completa
    except Exception as e:
        print("Error al abrir la imagen:", nombre)
        return None


def verificar_imagen_cargada():
    """
    Lanza excepción si aún no se ejecutó la función 1.
    """
    if ruta_imagen_cargada is None:
        raise RuntimeError("Debe ejecutar primero la FUNCIÓN 1 (cargar_imagen).")


def menu():
    while True:
        print("\n================ MENÚ PRINCIPAL ================")
        print("1) Cargar imagen (OBLIGATORIO)")
        print("2) Redimensionar imagen")
        print("3) Ajustar contraste")
        print("4) Aplicar filtros Pillow")
        print("5) Generar boceto de persona")
        print("6) Salir")
        print("================================================")

        op = input("Seleccione una opción (1-6): ").strip()

        if op == "1":
            print("\n--- CARGAR IMAGEN ---")
            cargar_imagen()

        elif op == "2":
            try:
                verificar_imagen_cargada()
                print("\n--- REDIMENSIONAR IMAGEN ---")
                print("Opciones de keyword: youtube / instagram / twitter / facebook")
                kw = input("Ingrese keyword: ").strip()
                redimensionar_imagen(ruta_imagen_cargada, kw)
            except RuntimeError as e:
                print(f"{e}")

        elif op == "3":
            try:
                verificar_imagen_cargada()
                print("\n--- AJUSTAR CONTRASTE ---")
                ajustar_contraste(ruta_imagen_cargada)
                print("Se ejecutó ajustar_contraste")
            except Exception as e:
                print(f"{e}")

        elif op == "4":
            try:
                verificar_imagen_cargada()
                print("\n--- APLICAR FILTRO PILLOW ---")
                print("Filtros: ORIGINAL, BLUR, CONTOUR, DETAIL, EDGE_ENHANCE, EDGE_ENHANCE_MORE,")
                print("         EMBOSS, FIND_EDGES, SHARPEN, SMOOTH")
                filtro = input("Ingrese el nombre del filtro: ").strip()
                aplicar_filtros(ruta_imagen_cargada, filtro)
            except RuntimeError as e:
                print(f"{e}")
            except ValueError as e:
                print(f"{e}")

        elif op == "5":
            try:
                verificar_imagen_cargada()
                print("\n--- BOCETO PERSONA ---")
                resp = input("¿La imagen contiene una persona? (s/n): ").strip().lower()
                persona = (resp == "s")
                boceto_persona(ruta_imagen_cargada, persona=persona, invertir=True)
            except RuntimeError as e:
                print(f"{e}")

        elif op == "6":
            print("Saliendo del programa...")
            break

        else:
            print("Opción inválida, elija entre 1 y 6.")
